
spring:
  data:
    neo4j:
      compiler: org.neo4j.ogm.compiler.MultiStatementCypherCompiler
      driver: org.neo4j.ogm.drivers.http.driver.HttpDriver
      uri: http://127.0.0.1:7474
      username: neo4j
      password: 123456

server:
  port: 31020

